"""intent_label nullable for intake emails

Revision ID: 5d0b776b5fe5
Revises: ea112922729f
Create Date: 2026-05-26 23:08:19.949695
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5d0b776b5fe5'
down_revision: str | None = 'ea112922729f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.alter_column('intent_label',
               existing_type=sa.VARCHAR(length=17),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.alter_column('intent_label',
               existing_type=sa.VARCHAR(length=17),
               nullable=False)

    # ### end Alembic commands ###
