"""initial schema

Revision ID: ea112922729f
Revises:
Create Date: 2026-05-22 08:26:35.187989
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ea112922729f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column(
            "account_tier", sa.Enum("Free", "Pro", "Enterprise", name="accounttier"), nullable=False
        ),
        sa.Column("registration_date", sa.DateTime(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("open_tickets_count", sa.Integer(), nullable=False),
        sa.Column("lifetime_value_usd", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("customer_id"),
    )
    op.create_table(
        "emails",
        sa.Column("email_id", sa.String(), nullable=False),
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column(
            "intent_label",
            sa.Enum(
                "Billing Query",
                "Order Status",
                "Technical Support",
                "Refund Request",
                "General FAQ",
                name="intentlabel",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "Unprocessed",
                "Processing",
                "Drafted",
                "Approved",
                "Rejected",
                "Sent",
                name="emailstatus",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.PrimaryKeyConstraint("email_id"),
    )
    op.create_table(
        "orders",
        sa.Column("order_id", sa.String(), nullable=False),
        sa.Column("customer_id", sa.String(), nullable=False),
        sa.Column("product_name", sa.String(), nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("Pending", "Shipped", "Delivered", "Cancelled", "Refunded", name="orderstatus"),
            nullable=False,
        ),
        sa.Column("order_date", sa.DateTime(), nullable=False),
        sa.Column("estimated_delivery_date", sa.DateTime(), nullable=True),
        sa.Column("tracking_number", sa.String(), nullable=True),
        sa.Column("amount_usd", sa.Float(), nullable=False),
        sa.Column(
            "payment_status",
            sa.Enum("Paid", "Pending", "Refunded", "Failed", name="paymentstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.PrimaryKeyConstraint("order_id"),
    )
    op.create_table(
        "drafts",
        sa.Column("draft_id", sa.String(), nullable=False),
        sa.Column("email_id", sa.String(), nullable=False),
        sa.Column(
            "intent",
            sa.Enum(
                "Billing Query",
                "Order Status",
                "Technical Support",
                "Refund Request",
                "General FAQ",
                name="intentlabel",
            ),
            nullable=True,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("final_body", sa.Text(), nullable=True),
        sa.Column("requires_human_review", sa.Boolean(), nullable=False),
        sa.Column("flags", sa.JSON(), nullable=False),
        sa.Column("model_used", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", "sent", name="draftstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["emails.email_id"],
        ),
        sa.PrimaryKeyConstraint("draft_id"),
    )
    op.create_table(
        "audit_events",
        sa.Column("audit_event_id", sa.String(), nullable=False),
        sa.Column("email_id", sa.String(), nullable=False),
        sa.Column("draft_id", sa.String(), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "classified",
                "drafted",
                "auto_approved",
                "approved",
                "edited_and_approved",
                "rejected",
                name="auditaction",
            ),
            nullable=False,
        ),
        sa.Column("agent_id", sa.String(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("edit_made", sa.Boolean(), nullable=False),
        sa.Column("original_draft_body", sa.Text(), nullable=True),
        sa.Column("final_body", sa.Text(), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["drafts.draft_id"],
        ),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["emails.email_id"],
        ),
        sa.PrimaryKeyConstraint("audit_event_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit_events")
    op.drop_table("drafts")
    op.drop_table("orders")
    op.drop_table("emails")
    op.drop_table("customers")
    # ### end Alembic commands ###
